version: '3.3'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: elixir-cloudflared
    restart: always
    networks:
      - proxy
    command: tunnel --config /etc/cloudflared/config.yml --no-autoupdate run elixir
    volumes:
      - ./config.yml:/etc/cloudflared/
  nginx:
    container_name: elixir-nginx
    image: nginx:latest
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - nginx-data:/usr/share/nginx/elixir.rocks:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  nginx-data:
    external: true

networks:
  proxy:
    driver: bridge
    external: true
