version: '3.3'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container-image: elixir-cloudflared
    restart: always
    networks:
      - proxy
    command: tunnel --config /cloudflared/ --no-autoupdate run --token ${{ secrets.CLOUDFLARED_TOKEN }}
    volumes:
      - /opt/cloudflared/:/etc/cloudflared/
  nginx:
    container_name: elixir-nginx
    image: nginx:latest
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - nginx-data:/usr/share/nginx/elixir.rocks:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends-on:
      - cloudflared

volumes:
  nginx-data:
    external: true

networks:
  proxy:
    driver: bridge
    external: true
